#!/bin/bash
set -eu # exit script on errors

echo "copy spamtube .env.local"
rsync /home/git/www/spamtube/backend/.env.local ./backend/.env.local

# build frontend is done with github actions
# echo "> npm run build..."
# cd frontend && npm run build && cd ..

# build backend
echo "> go build..."
cd backend && go build -o ./server && cd ..

export MAIN="backend/server"