version: "3.1"

services:
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src
    environment:
      BACKEND_URL: "http://backend:3000"
      BACKEND_WS_URL: "ws://localhost:8080/ws"
    networks:
      - spamtube-devnet
    depends_on:
      - backend

  build-ui:
    build: frontend
    command: ["npm", "run", "build"]
    networks:
      - spamtube-devnet
    volumes:
      - ui-volume:/app/dist

  backend:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ui-volume:/app/dist
    networks:
      - spamtube-devnet
    environment:
      PORT: 3000
    depends_on:
      migrate:
        condition: service_completed_successfully

  migrate:
    build: database
    networks:
      - spamtube-devnet
    environment:
      DATABASE_URL: postgres://postgres:postgres@pg-spamtube/spamtube_db?sslmode=disable
    depends_on:
      pg-spamtube:
        condition: service_healthy

  pg-spamtube:
    image: postgres:10.3
    restart: always
    ports:
      - 5337:5432
    networks:
      - spamtube-devnet
    environment:
      POSTGRES_DB: spamtube_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ui-volume:

networks:
  spamtube-devnet:
    driver: bridge
