version: "3.1"

services:
  chatgpt:
    build: chatgpt
    environment:
      GOOGLE_EMAIL: ${GOOGLE_EMAIL}
      GOOGLE_PASSWORD: ${GOOGLE_PASSWORD}
      VOICE_INPUT: ${VOICE_INPUT}
    volumes:
      - chatgpt-volume:/app/out

  image-ai-maker:
    build: image-ai-maker
    volumes: 
      - image-xs-volume:/app/out
    environment:
      IMAGE_INPUT: ${IMAGE_INPUT}

  image-upscaler:
    build: image-upscaler
    volumes:
      - image-xs-volume:/app/data
      - image-xl-volume:/app/out
    depends_on:
      image-ai-maker:
        condition: service_completed_successfully

  voice-maker:
    build: voice-maker
    volumes:
      - chatgpt-volume:/app/data
      - voice-volume:/app/out
    depends_on:
      chatgpt:
        condition: service_completed_successfully

  subtitle-maker:
    build: subtitle-maker
    volumes:
      - chatgpt-volume:/app/data
      - subs-volume:/app/out
    depends_on:
      chatgpt:
        condition: service_completed_successfully

  music-maker:
    build: music-maker
    volumes:
      - music-volume:/app/out

  generator:
    build: generator
    volumes:
      - image-xl-volume:/app/data/images
      - subs-volume:/app/data/subtitles
      - voice-volume:/app/data/audio/voice
      - music-volume:/app/data/audio/music
      - video-volume:/app/out
    environment:
      IMAGE_EXT: "png"
    depends_on:
      image-upscaler:
        condition: service_completed_successfully
      voice-maker:
        condition: service_completed_successfully
      music-maker:
        condition: service_completed_successfully
      subtitle-maker:
        condition: service_completed_successfully

  uploader:
    build: uploader
    volumes:
      - chatgpt-volume:/app/data/chatgpt
      - video-volume:/app/data/video
      - uploader-volume:/app/out
    environment:
      FILENAME: ./data/video/video.mp4
      TITLE: ${TITLE}
      TITLE_PATH: ./data/chatgpt/title.txt
      DESCRIPTION: ${DESCRIPTION}
    depends_on:
      generator:
        condition: service_completed_successfully

  notifier:
    build: notifier
    volumes:
      - uploader-volume:/app/data
    environment:
      SLACK_POST_TITLE: "${TITLE} :tv:"
      SLACK_POST_BODY: "${DESCRIPTION}\n\n${IMAGE_INPUT}"
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    depends_on:
      uploader:
        condition: service_completed_successfully

volumes:
  image-xs-volume:
  image-xl-volume:
  voice-volume:
  music-volume:
  video-volume:
  subs-volume:
  chatgpt-volume:
  uploader-volume:
