version: "3.1"

services:
  build-frontend:
    build: frontend
    command: ["npm", "run", "build"]
    volumes:
      - ./frontend/dist:/app/dist

  build-backend:
    build: backend
    command: ["go", "build", "-o", "./dist/server"]
    volumes:
      - ./backend/dist:/app/dist

  build-migrate:
    build: database
    command: ["go", "build", "-o", "./dist/migrate"]
    volumes:
      - ./database/dist:/app/dist

  build-generator:
    build: generator
    command: ["go", "build", "-o", "./dist/generator"]
    volumes:
      - ./generator/dist:/app/dist
