version: "3.1"

services:
  chatgpt:
    build: chatgpt
    environment:
      GOOGLE_EMAIL: ${GOOGLE_EMAIL}
      GOOGLE_PASSWORD: ${GOOGLE_PASSWORD}
      TITLE: ${TITLE}
      VOICE_INPUT: ${VOICE_INPUT}
    volumes:
      - data-volume:/app/out

  image-finder:
    build: image-finder
    volumes:
      - image-volume:/app/out
    environment:
      IMAGE_INPUT: ${IMAGE_INPUT}
      UNSPLASH_ACCESS_TOKEN: ${UNSPLASH_ACCESS_TOKEN}

  image-upscaler:
    build: image-upscaler
    volumes:
      - image-volume:/app/data
      - image-upscaled-volume:/app/out
    depends_on:
      image-finder:
        condition: service_completed_successfully

  image-uploader:
    build: image-uploader
    volumes:
      - image-upscaled-volume:/app/data
    environment:
      IMGBB_API_KEY: ${IMGBB_API_KEY}
    depends_on:
      image-finder:
        condition: service_completed_successfully

  voice-maker:
    build: voice-maker
    volumes:
      - data-volume:/app/data
      - voice-volume:/app/out
    depends_on:
      chatgpt:
        condition: service_completed_successfully

  subtitle-maker:
    build: subtitle-maker-from-voice
    volumes:
      # - data-volume:/app/data
      - voice-volume:/app/data
      - subs-volume:/app/out
    depends_on:
      voice-maker:
        condition: service_completed_successfully

  music-maker:
    build: music-maker
    volumes:
      - music-volume:/app/out

  generator:
    build: generator
    volumes:
      - image-upscaled-volume:/app/data/images
      - subs-volume:/app/data/subtitles
      - voice-volume:/app/data/audio/voice
      - music-volume:/app/data/audio/music
      - video-volume:/app/out
    depends_on:
      image-uploader:
        condition: service_completed_successfully
      voice-maker:
        condition: service_completed_successfully
      music-maker:
        condition: service_completed_successfully
      subtitle-maker:
        condition: service_completed_successfully

  uploader:
    build: uploader
    volumes:
      - data-volume:/app/data/chatgpt
      - video-volume:/app/data/video
      - uploader-volume:/app/out
    environment:
      FILENAME: ./data/video/video.mp4
      TITLE: ${TITLE}
      TITLE_PATH: ./data/chatgpt/title.txt
      DESCRIPTION: ${DESCRIPTION}
    depends_on:
      generator:
        condition: service_completed_successfully

  notifier:
    build: notifier
    volumes:
      - uploader-volume:/app/data
    environment:
      SLACK_POST_TITLE: "${TITLE} :tv:"
      SLACK_POST_BODY: "${DESCRIPTION}\n\n${IMAGE_INPUT}"
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    depends_on:
      uploader:
        condition: service_completed_successfully

volumes:
  data-volume:
  image-volume:
  voice-volume:
  subs-volume:
  music-volume:
  video-volume:
  uploader-volume:
  image-upscaled-volume:
  
