name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Add dummy youtube credentials
        run: |
          mkdir .credentials
          echo "${CLIENT_SECRETS}" > .credentials/client_secrets.json
          echo "${YOUTUBE_TOKEN}" > .credentials/youtube_token.json
        working-directory: uploader
        env:
          CLIENT_SECRETS: '{}'
          YOUTUBE_TOKEN: '{}'

      - name: Docker is baking small cake
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx bake \
            --load \
            --file docker-compose.yml

      - name: Docker is baking big cake
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx bake \
            --load \
            --file docker-compose.yml \
            --file docker-compose-upload.yml
