name: build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - run: |
          docker buildx bake \
            --set "*.cache-from=type=gha" \
            --set "*.cache-to=type=gha,mode=max" \
            --load \
            -f docker-compose.yaml
