name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and cache frontend dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - uses: actions/upload-artifact@v3
        with:
          name: dist-frontend
          path: "*/dist"

  build-backend:
    name: Build backend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.18']

    steps:
      - uses: actions/checkout@v2
      - name: Use go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          architecture: arm

      - name: Build backend
        run: go build -o ./dist/server
        working-directory: backend

      - uses: actions/upload-artifact@v3
        with:
          name: dist-backend
          path: "*/dist"

  deploy:
    needs: [build-frontend, build-backend]

    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          ref: "master"

      - uses: actions/download-artifact@v2
        with:
          name: dist-frontend

      - uses: actions/download-artifact@v2
        with:
          name: dist-backend

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Push to Server
        run: |
          git remote add server git@zolly.ml:repos/spamtube.git
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git add */dist -f
          git commit -m "Build files"
          git push -u server master -f
