name: Test - remove

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
      
jobs:
  upload-flow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SET
        run: |
          echo VIDEO_URL: "${VIDEO_URL}"
          echo "VIDEO_URL=${VIDEO_URL}" >> $GITHUB_ENV
        env:
          VIDEO_URL: "https://www.youtube.com/watch?v=NBKOiLQ3g8Y"

      - name: ENV
        run: |
          echo VIDEO_URL ENV: "${{ env.VIDEO_URL }}"
      
      # - name: Post to slack
      #   run: |
      #     curl -X POST \
      #       -H 'Content-type: application/json' \
      #       --data '{ "text": "${{ env.VIDEO_URL }}" }' \
      #       ${{ secrets.slack_webhook }}