name: Test - remove

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
      
jobs:
  upload-flow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      - name: Input variables
        run: |
          echo TITLE: "${TITLE}"
          echo DESCRIPTION: "${DESCRIPTION}"
          echo IMAGE_INPUT: "${IMAGE_INPUT}"
          echo VOICE_INPUT: "${VOICE_INPUT}"
          export VIDEO_URL = "https://www.youtube.com/watch?v=NBKOiLQ3g8Y"
          echo VIDEO_URL: "${VIDEO_URL}"
        env:
          TITLE: ${{ inputs.title }}
          DESCRIPTION: ${{ inputs.description }}
          IMAGE_INPUT: ${{ inputs.image }}
          VOICE_INPUT: ${{ inputs.voice }}
      
      - name: Post to slack
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{ "text": "${VIDEO_URL}" }' \
            ${{ secrets.slack_webhook }}