name: Trigger Content Flow

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      title:
        description: "Title of video"
        required: true
        type: string
      description:
        description: "Description of video"
        required: true
        type: string
      image_keywords:
        description: "Image keywords of video"
        required: true
        type: string
      text_content:
        description: "Text content of video"
        required: true
        type: string
      custom_voice:
        description: "Voice of video"
        required: false
        type: string
      custom_style:
        description: "Custom style"
        required: false
        type: string
      custom_background:
        description: "Custom background"
        required: false
        type: string

jobs:
  upload-flow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Input variables
        run: |
          echo TITLE: "${TITLE}"
          echo DESCRIPTION: "${DESCRIPTION}"
          echo IMAGE_KEYWORDS: "${IMAGE_KEYWORDS}"
          echo TEXT_CONTENT: "${TEXT_CONTENT}"
          echo CUSTOM_VOICE: "${CUSTOM_VOICE}"
          echo CUSTOM_STYLE: "${CUSTOM_STYLE}"
          echo CUSTOM_BACKGROUND: "${CUSTOM_BACKGROUND}"
        env:
          TITLE: ${{ inputs.title }}
          DESCRIPTION: ${{ inputs.description }}
          IMAGE_KEYWORDS: ${{ inputs.image_keywords }}
          TEXT_CONTENT: ${{ inputs.text_content }}
          CUSTOM_VOICE: ${{ inputs.custom_voice }}
          CUSTOM_STYLE: ${{ inputs.custom_style }}
          CUSTOM_BACKGROUND: ${{ inputs.custom_background }}

      - name: Add youtube credentials
        run: |
          mkdir .credentials
          echo "${CLIENT_SECRETS}" > .credentials/client_secrets.json
          echo "${YOUTUBE_TOKEN}" > .credentials/youtube_token.json
        working-directory: uploader
        env:
          CLIENT_SECRETS: ${{ secrets.client_secrets }}
          YOUTUBE_TOKEN: ${{ secrets.youtube_token }}

      - name: Docker is baking a cake
        run: |
          docker buildx bake \
            --load \
            --file docker-compose-upload.yml

      - name: Docker is running upload!
        run: docker compose -f docker-compose-upload.yml up
        env:
          TITLE: ${{ inputs.title }}
          DESCRIPTION: ${{ inputs.description }}
          IMAGE_KEYWORDS: ${{ inputs.image_keywords }}
          TEXT_CONTENT: ${{ inputs.text_content }}
          CUSTOM_VOICE: ${{ inputs.custom_voice }}
          CUSTOM_STYLE: ${{ inputs.custom_style }}
          CUSTOM_BACKGROUND: ${{ inputs.custom_background }}
          GOOGLE_EMAIL: ${{ secrets.google_email }}
          GOOGLE_PASSWORD: ${{ secrets.google_password }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook }}
          UNSPLASH_ACCESS_TOKEN: ${{ secrets.unsplash_access_token }}
          IMGBB_API_KEY: ${{ secrets.imgbb_api_key }}
