name: Trigger Content Flow

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of video'
        required: true 
        type: string
      description:
        description: 'Description of video'
        required: true 
        type: string
      image:
        description: 'Image of video'
        required: true 
        type: string
      voice:
        description: 'Voice of video'
        required: true 
        type: string
      
jobs:
  upload-flow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Input variables
        run: |
          echo TITLE: "${TITLE}"
          echo DESCRIPTION: "${DESCRIPTION}"
          echo IMAGE_INPUT: "${IMAGE_INPUT}"
          echo VOICE_INPUT: "${VOICE_INPUT}"
        env:
          TITLE: ${{ inputs.title }}
          DESCRIPTION: ${{ inputs.description }}
          IMAGE_INPUT: ${{ inputs.image }}
          VOICE_INPUT: ${{ inputs.voice }}
      
      - name: Add youtube credentials
        run: |
          mkdir .credentials
          echo "${CLIENT_SECRETS}" > .credentials/client_secrets.json
          echo "${YOUTUBE_TOKEN}" > .credentials/youtube_token.json
        working-directory: uploader
        env:
          CLIENT_SECRETS: ${{ secrets.client_secrets }}
          YOUTUBE_TOKEN: ${{ secrets.youtube_token }}

      - name: Docker is baking a cake
        run: |
          docker buildx bake \
            --set "*.cache-from=type=gha" \
            --set "*.cache-to=type=gha,mode=max" \
            --load \
            -f docker-compose-upload.yml

      - name: Docker is running upload!
        run: |
          docker compose -f docker-compose-upload.yml up
          echo "${VIDEO_URL}" >> $GITHUB_ENV
        env:
          TITLE: ${{ inputs.title }}
          DESCRIPTION: ${{ inputs.description }}
          IMAGE_INPUT: ${{ inputs.image }}
          VOICE_INPUT: ${{ inputs.voice }}

      - name: Post to slack
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{ "text": "${VIDEO_URL}" }' \
            ${{ secrets.slack_webhook }}